name: Build from Official 7-Zip Repo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Git
        run: choco install git -y

      - name: 获取最新版本
        shell: pwsh
        run: |
          $tag = (Invoke-RestMethod https://api.github.com/repos/ip7z/7zip/releases/latest).tag_name
          $verFile = "7z$($tag -replace '\.','')"
          Set-Content 7zVer.txt $verFile
          echo "VERSION=$verFile" >> $env:GITHUB_ENV
          echo "VERSION_TAG=$tag" >> $env:GITHUB_ENV

      - name: 准备源码（官方GitHub）
        shell: pwsh
        run: .\Prepare.ps1 -BuildVersion (Get-Content 7zVer.txt)

      - name: 编译
        shell: pwsh
        run: .\Build.ps1 -BuildVersion (Get-Content 7zVer.txt)

      - name: 打包（不压缩）
        shell: pwsh
        run: .\Pack.ps1 -BuildVersion (Get-Content 7zVer.txt)

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          name: "7-Zip ${{ env.VERSION_TAG }}"
          tag_name: "${{ env.VERSION_TAG }}"
          files: ./*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
